config/routes.rb
Impressbox::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  match '/home',  to: 'static_pages#home'
  match '/help',  to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = user.email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		flash.now[:error] = "Invalid email password combination"
		render 'new'
	end

	def destroy
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
   def show
      @user = User.find(params[:id])
   end

   def new
   	@user = User.new
   end

   def create
   	@user = User.new(params[:user])
   	if @user.save
         flash[:success] = "Welcome to Impressbox"
			redirect_to @user 
		else
	   	render 'new'
   	end
   end

end

app/helpers/application_helper.rb
#require 'spec_helper'

module ApplicationHelper
  
  def full_title(page_title)
    base_title = "Hi, i'm Impressbox"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns thr gravatar for thr given user

	def gravatar_for(user, options = { size: 50 })
	   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	   size = options[:size]
	   gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	   image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_header.html.erb
<div class="header">
	<nav>
		<span>
		<%= link_to "impressbox", root_path, id: "logo" %>
		</span>
		<ul>
			<li><%= link_to "home",  home_path %></li>
			<li><%= link_to "help",  'help' %></li>
			<li><%= link_to "about", about_path %></li>
		</ul>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
		<div class="header">
			<%= render 'layouts/header' %>
		</div>

		<div class="container">
         <% flash.each do |key, value| %>
         <!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
         <%= content_tag(:div, value, class: "alert alert-#{key}") %>
         <% end %>
			
			<%= yield %>
			<%= debug(params) if Rails.env.development? %>	
		</div>

		<div>sdfg</div>
		<div>sdfg sdflksdjf</div>
		safdasdf;aslkj;l

	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %> 
	<div id="error_explanation">
		
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %><li>
			<% end %>
		</ul>
	</div>

<% end %>

app/views/static_pages/.html.erb
<h1>StaticPages#\</h1>
<p>Find me in app/views/static_pages\.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, 'About page') %>

<div class="content">
	<h1>This is about Impressbox page</h1>
	<p>Find me in app/views/static_pages/home.html.erb</p>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home page') %>

<div class="container">	

	<h1>Impressbox first steps</h1>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
	<p>
		Find me in app/views/static_pages/home.html.erb
	</p>
</div>

app/views/users/.html.erb
<h1>Users#\</h1>
<p>Find me in app/views/users\.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<p>New Users comes here</p>

<div class="row">
	<div class="span6 offset3">
	
		<%= form_for(@user) do |f| %>\
			
			<div class="inputs-block">
				<%= render 'shared/error_messages' %>
				<%= f.label :name %>
				<%= f.text_field :name %>
				
				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>
			</div>

			<%= f.submit "Create my account", class: "btn btn-large" %>

		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<!-- <%= @user.name %>, <%= @user.email %> -->

<% provide(:title, @user.name) %>

<div class="content">
	<h1>
		<%= gravatar_for @user, size: 60 %>
		<%= @user.name%>
	</h1>

	<p>Find me in app/views/static_pages/home.html.erb</p>
</div>